# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_headquater', models.BooleanField(default=False)),
                ('street', models.CharField(blank=True, max_length=256)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_office', to='company.Company')),
            ],
        ),
    ]
