# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='is_headquater',
            new_name='headquater',
        ),
    ]
